/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package lab_cao2;
import Model.Customer;
import Model.DeliveryPackage;
import Model.Product;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author caofei
 */
public class EditJPanel extends javax.swing.JPanel {
    private DeliveryPackage delPackage;
    private Product productViewed;


    /**
     * Creates new form EditJPanel
     */
    public EditJPanel() {
        initComponents();
    }
    EditJPanel(DeliveryPackage deliveryPackage) {
        initComponents();
        this.delPackage = deliveryPackage;
        displayProductList();      
        displayPackageDetails();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        packageId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        packageWt = new javax.swing.JTextField();
        custName1 = new javax.swing.JTextField();
        custId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        productComboBox = new javax.swing.JComboBox();
        btnShow = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        productId1 = new javax.swing.JTextField();
        productName1 = new javax.swing.JTextField();
        productPrice1 = new javax.swing.JTextField();
        btnUpdateProduct = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 255, 51));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Package Id");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        jLabel7.setText("Customer name");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, -1, 20));
        add(packageId, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 100, 30));

        jLabel3.setText("weight");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));
        add(packageWt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 100, 30));
        add(custName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, 130, 30));
        add(custId, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, 130, 30));

        jLabel1.setText("ID");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, -1, 20));

        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 90, 20));

        add(productComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 150, 30));

        btnShow.setText("Show");
        btnShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowActionPerformed(evt);
            }
        });
        add(btnShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 80, 30));

        jLabel4.setText("ProdId");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, 20));

        jLabel5.setText("ProdName");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, 20));

        jLabel6.setText("ProdPrice");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, -1, 20));
        add(productId1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 110, 30));
        add(productName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 110, 30));
        add(productPrice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 110, 30));

        btnUpdateProduct.setText("Update Product");
        btnUpdateProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateProductActionPerformed(evt);
            }
        });
        add(btnUpdateProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 150, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:

        String id = packageId.getText();
        String weight = packageWt.getText();
        String customerId = custId.getText();
        String customername = custName1.getText();

        // store the data
        this.delPackage.setPackageId(Integer.valueOf(id));
        this.delPackage.setPackageWeight(Double.valueOf(weight));

        Customer customer = this.delPackage.getCustomer();
        customer.setCustomerId(Integer.valueOf(customerId));
        customer.setFullName(customername);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowActionPerformed
        // TODO add your handling code here:

        productId1.setEnabled(false);

        int pid = (int) productComboBox.getSelectedItem();
        Product prod = this.delPackage.findProduct(pid);
        this.productViewed = prod;
        if (!prod.equals(null)) {
            productId1.setText(String.valueOf(pid));
            productName1.setText(prod.getProductName());
            productPrice1.setText(String.valueOf(prod.getPrice()));
        } else {
            JOptionPane.showMessageDialog(null, "Product not found");
        }
    }//GEN-LAST:event_btnShowActionPerformed

    private void btnUpdateProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateProductActionPerformed
        // TODO add your handling code here:

        this.productViewed.setProductName(productName1.getText());
        this.productViewed.setPrice(Double.valueOf(productPrice1.getText()));

    }//GEN-LAST:event_btnUpdateProductActionPerformed
public void displayProductList() {

        for (Product p : this.delPackage.getProductList()) {
            productComboBox.addItem(p.getProductId());
        }

    }

    public void displayPackageDetails() {
        packageId.setText(String.valueOf(this.delPackage.getPackageId()));
        packageWt.setText(String.valueOf(this.delPackage.getPackageWeight()));

        Customer customer = this.delPackage.getCustomer();
        custId.setText(String.valueOf(customer.getCustomerId()));
        custName1.setText(customer.getFullName());

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnShow;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnUpdateProduct;
    private javax.swing.JTextField custId;
    private javax.swing.JTextField custName1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField packageId;
    private javax.swing.JTextField packageWt;
    private javax.swing.JComboBox productComboBox;
    private javax.swing.JTextField productId1;
    private javax.swing.JTextField productName1;
    private javax.swing.JTextField productPrice1;
    // End of variables declaration//GEN-END:variables
}
