/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;
import Model.Address;
import Model.Contact;
import Model.Person;

/**
 *
 * @author caofei
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    private Person person;
    
    
    public MainJFrame() {
        initComponents();
        this.person=new Person();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        ViewJPanel = new javax.swing.JPanel();
        viewNuid = new javax.swing.JLabel();
        viewfirstName = new javax.swing.JLabel();
        viewlastName = new javax.swing.JLabel();
        viewcollegeName = new javax.swing.JLabel();
        viewofficePhone = new javax.swing.JLabel();
        viewpersonPhone = new javax.swing.JLabel();
        viewofficeEmail = new javax.swing.JLabel();
        viewpersonEmail = new javax.swing.JLabel();
        viewcurrentStreet = new javax.swing.JLabel();
        viewcurrentApt = new javax.swing.JLabel();
        viewcurrentCity = new javax.swing.JLabel();
        viewcurrentZip = new javax.swing.JLabel();
        viewpermStreet = new javax.swing.JLabel();
        viewpermApt = new javax.swing.JLabel();
        viewpermCity = new javax.swing.JLabel();
        viewpermZip = new javax.swing.JLabel();
        CreateJPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        SaveBtn = new javax.swing.JButton();
        fieldNuid = new javax.swing.JTextField();
        fieldfirstName = new javax.swing.JTextField();
        fieldlastName = new javax.swing.JTextField();
        fieldCollege = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        fieldofficePhone = new javax.swing.JTextField();
        fieldpersonPhone = new javax.swing.JTextField();
        fieldofficeEmail = new javax.swing.JTextField();
        fieldcurrentStreet = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        fieldpersonEmail = new javax.swing.JTextField();
        fieldcurrentApt = new javax.swing.JTextField();
        fieldcurrentCity = new javax.swing.JTextField();
        fieldcurrentZip = new javax.swing.JTextField();
        fieldpermStreet = new javax.swing.JTextField();
        fieldpermApt = new javax.swing.JTextField();
        fieldpermCity = new javax.swing.JTextField();
        fieldpermZip = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        viewNuid.setText("jLabel37");

        viewfirstName.setText("jLabel38");

        viewlastName.setText("jLabel38");

        viewcollegeName.setText("jLabel38");

        viewofficePhone.setText("jLabel38");

        viewpersonPhone.setText("jLabel38");

        viewofficeEmail.setText("jLabel38");

        viewpersonEmail.setText("jLabel38");

        viewcurrentStreet.setText("jLabel38");

        viewcurrentApt.setText("jLabel38");

        viewcurrentCity.setText("jLabel38");

        viewcurrentZip.setText("jLabel38");

        viewpermStreet.setText("jLabel38");

        viewpermApt.setText("jLabel38");

        viewpermCity.setText("jLabel38");

        viewpermZip.setText("jLabel38");

        javax.swing.GroupLayout ViewJPanelLayout = new javax.swing.GroupLayout(ViewJPanel);
        ViewJPanel.setLayout(ViewJPanelLayout);
        ViewJPanelLayout.setHorizontalGroup(
            ViewJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewJPanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(ViewJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewNuid)
                    .addComponent(viewpersonEmail)
                    .addComponent(viewofficeEmail)
                    .addComponent(viewpersonPhone)
                    .addComponent(viewofficePhone)
                    .addComponent(viewcollegeName)
                    .addComponent(viewlastName)
                    .addComponent(viewfirstName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addGroup(ViewJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ViewJPanelLayout.createSequentialGroup()
                        .addGroup(ViewJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(viewcurrentStreet)
                            .addComponent(viewcurrentApt)
                            .addComponent(viewcurrentCity)
                            .addComponent(viewcurrentZip))
                        .addGap(103, 103, 103))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ViewJPanelLayout.createSequentialGroup()
                        .addGroup(ViewJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(viewpermApt)
                            .addComponent(viewpermStreet)
                            .addComponent(viewpermCity)
                            .addComponent(viewpermZip))
                        .addGap(95, 95, 95))))
        );
        ViewJPanelLayout.setVerticalGroup(
            ViewJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewJPanelLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(ViewJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewNuid)
                    .addComponent(viewcurrentStreet))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ViewJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewfirstName)
                    .addComponent(viewcurrentApt))
                .addGap(18, 18, 18)
                .addGroup(ViewJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewlastName)
                    .addComponent(viewcurrentCity))
                .addGap(27, 27, 27)
                .addGroup(ViewJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewcollegeName)
                    .addComponent(viewcurrentZip))
                .addGap(49, 49, 49)
                .addGroup(ViewJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewofficePhone)
                    .addComponent(viewpermStreet))
                .addGap(18, 18, 18)
                .addGroup(ViewJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewpersonPhone)
                    .addComponent(viewpermApt))
                .addGap(32, 32, 32)
                .addGroup(ViewJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewofficeEmail)
                    .addComponent(viewpermCity))
                .addGap(37, 37, 37)
                .addGroup(ViewJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewpersonEmail)
                    .addComponent(viewpermZip))
                .addContainerGap(108, Short.MAX_VALUE))
        );

        jSplitPane1.setRightComponent(ViewJPanel);

        jLabel1.setText("NU ID");

        jLabel2.setText("First Name");

        jLabel3.setText("Last Name");

        jLabel4.setText("College Name");

        SaveBtn.setText("SAVE");
        SaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtnActionPerformed(evt);
            }
        });

        jLabel5.setText("office phone");

        jLabel6.setText("person phone");

        jLabel7.setText("office email");

        jLabel8.setText("person email");

        jLabel9.setText("street");

        jLabel10.setText("apt.no");

        jLabel11.setText("city/state");

        jLabel12.setText("zipcode");

        jLabel13.setText("street");

        jLabel14.setText("apt.no");

        jLabel15.setText("city/state");

        jLabel16.setText("zipcode");

        jLabel17.setText("current");

        jLabel18.setText("permanent");

        javax.swing.GroupLayout CreateJPanelLayout = new javax.swing.GroupLayout(CreateJPanel);
        CreateJPanel.setLayout(CreateJPanelLayout);
        CreateJPanelLayout.setHorizontalGroup(
            CreateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CreateJPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(CreateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CreateJPanelLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(120, 120, 120))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CreateJPanelLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(121, 121, 121))))
            .addGroup(CreateJPanelLayout.createSequentialGroup()
                .addGroup(CreateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CreateJPanelLayout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(CreateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CreateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3)
                                .addGroup(CreateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)))
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(10, 10, 10)
                        .addGroup(CreateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(fieldCollege)
                            .addComponent(fieldlastName)
                            .addComponent(fieldfirstName, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(fieldofficePhone, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldpersonPhone, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldofficeEmail, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldNuid, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldpersonEmail, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(52, 52, 52)
                        .addGroup(CreateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addGroup(CreateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CreateJPanelLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(CreateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fieldcurrentApt, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fieldcurrentStreet, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fieldcurrentCity, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fieldcurrentZip, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fieldpermStreet, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fieldpermApt, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CreateJPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(CreateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fieldpermZip, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fieldpermCity, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(CreateJPanelLayout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(SaveBtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CreateJPanelLayout.setVerticalGroup(
            CreateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreateJPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addGroup(CreateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fieldNuid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(fieldcurrentStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CreateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fieldfirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(fieldcurrentApt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CreateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(fieldlastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(fieldcurrentCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CreateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(fieldCollege, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(fieldcurrentZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CreateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(fieldofficePhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(fieldpermStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CreateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(fieldpersonPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(fieldpermApt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CreateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(fieldofficeEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(fieldpermCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(CreateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel16)
                    .addComponent(fieldpersonEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldpermZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(SaveBtn)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(CreateJPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtnActionPerformed
        // TODO add your handling code here:
        String nuid=fieldNuid.getText();
        String firstName=fieldfirstName.getText();
        String lastName=fieldlastName.getText();
        String collegeName=fieldCollege.getText();
        
        long officePhone=Long.valueOf(fieldofficePhone.getText());
        long personPhone=Long.valueOf(fieldpersonPhone.getText());
        String personEmail=fieldpersonEmail.getText();
        String officeEmail=fieldofficeEmail.getText();
        
        String streetname=fieldcurrentStreet.getText();
        String permstreet=fieldpermStreet.getText();
        String aptNo=fieldcurrentApt.getText();
        
        String permApt=fieldpermApt.getText();
        String city=fieldcurrentCity.getText();
        String permcity=fieldpermCity.getText();
        String zip=fieldcurrentZip.getText();
        String permZip=fieldpermZip.getText();
        
        this.person.setNuid(nuid);
        this.person.setFirstName(firstName);
        this.person.setLastName(lastName);
        this.person.setCollegeName(collegeName);
        
        Address address=this.person.getAddress();
        address.setStreet(streetname);
        address.setAptNo(aptNo);
        address.setCity(city);
        address.setZipCode(zip);
        
        Address permanentAddress=this.person.getPermanentAddress();
        permanentAddress.setStreet(permstreet);
        permanentAddress.setAptNo(permApt);
        permanentAddress.setCity(permcity);
        permanentAddress.setZipCode(permZip);
        
        Contact officeContact=this.person.getOfficeContact();
        officeContact.setEmailID(officeEmail);
        officeContact.setPhoneNumber(officePhone);
        
       
        
        Contact localContact=this.person.getPersonContact();
        localContact.setEmailID(personEmail);
        localContact.setPhoneNumber(personPhone);
        
        display();
    }
    
    private void display(){
        viewNuid.setText(this.person.getNuid());
        viewfirstName.setText(this.person.getFirstName());
        viewlastName.setText(this.person.getLastName());
        viewcollegeName.setText(this.person.getCollegeName());
        
        viewpersonPhone.setText(String.valueOf(this.person.getPersonContact().getPhoneNumber()));
        viewofficePhone.setText(String.valueOf(this.person.getOfficeContact().getPhoneNumber()));
        
        viewpersonEmail.setText(this.person.getPersonContact().getEmailID());
        viewofficeEmail.setText(this.person.getOfficeContact().getEmailID());
        
        viewcurrentStreet.setText(this.person.getAddress().getStreet());
        viewpermStreet.setText(this.person.getPermanentAddress().getStreet());
        
        viewcurrentApt.setText(this.person.getAddress().getAptNo());
        viewpermApt.setText(this.person.getPermanentAddress().getAptNo());
        
        viewcurrentCity.setText(this.person.getAddress().getCity());
        viewpermCity.setText(this.person.getPermanentAddress().getCity());
        
        viewcurrentZip.setText(this.person.getAddress().getZipCode());
        viewpermZip.setText(this.person.getPermanentAddress().getZipCode());
    
        
                
        
        
        
      
        
        
        
    }//GEN-LAST:event_SaveBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CreateJPanel;
    private javax.swing.JButton SaveBtn;
    private javax.swing.JPanel ViewJPanel;
    private javax.swing.JTextField fieldCollege;
    private javax.swing.JTextField fieldNuid;
    private javax.swing.JTextField fieldcurrentApt;
    private javax.swing.JTextField fieldcurrentCity;
    private javax.swing.JTextField fieldcurrentStreet;
    private javax.swing.JTextField fieldcurrentZip;
    private javax.swing.JTextField fieldfirstName;
    private javax.swing.JTextField fieldlastName;
    private javax.swing.JTextField fieldofficeEmail;
    private javax.swing.JTextField fieldofficePhone;
    private javax.swing.JTextField fieldpermApt;
    private javax.swing.JTextField fieldpermCity;
    private javax.swing.JTextField fieldpermStreet;
    private javax.swing.JTextField fieldpermZip;
    private javax.swing.JTextField fieldpersonEmail;
    private javax.swing.JTextField fieldpersonPhone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel viewNuid;
    private javax.swing.JLabel viewcollegeName;
    private javax.swing.JLabel viewcurrentApt;
    private javax.swing.JLabel viewcurrentCity;
    private javax.swing.JLabel viewcurrentStreet;
    private javax.swing.JLabel viewcurrentZip;
    private javax.swing.JLabel viewfirstName;
    private javax.swing.JLabel viewlastName;
    private javax.swing.JLabel viewofficeEmail;
    private javax.swing.JLabel viewofficePhone;
    private javax.swing.JLabel viewpermApt;
    private javax.swing.JLabel viewpermCity;
    private javax.swing.JLabel viewpermStreet;
    private javax.swing.JLabel viewpermZip;
    private javax.swing.JLabel viewpersonEmail;
    private javax.swing.JLabel viewpersonPhone;
    // End of variables declaration//GEN-END:variables
}
